[package]
name = "fungui"
version = "0.1.0"
authors = ["Jens Pitkanen <jens@neon.moe>"]

[dependencies]
png = "0.12"
lazy_static = "1.1"
rusttype = { version = "0.7", features = ["gpu_cache"] }
unicode-normalization = "0.1"
glutin = { version = "0.18", optional = true }
clipboard = { version = "0.5", optional = true }

[build-dependencies]
gl_generator = "0.9"

[features]
default = ["window_bootstrap", "default_resources", "clipboard"]
window_bootstrap = ["glutin"]
default_resources = []
